#ifdef DEBUG
#define new DEBUG
#endif

IMPLEMENT_DYNAMIC(CMainFrame, CFrameWnd)

BEGIN_MESSAGE_MAP(CMainFrame, CFrameWnd)
	ON_WM_CREATE()
	ON_WM_SETFOCUS()

	ON_COMMAND(ID_REG_RIGHT_DELETE, OnRegRightDelete)
	ON_UPDATE_COMMAND_UI(ID_REG_RIGHT_DELETE, OnUpdateRegRightDelete)
	ON_COMMAND(ID_REG_LEFT_DELETE, OnRegLeftDelete)
	ON_COMMAND(ID_REG_RIGHT_CREATE_BIN, OnRegRightCreateBin)
	ON_COMMAND(ID_REG_RIGHT_CREATE_STR, OnRegRightCreateStr)
	ON_COMMAND(ID_REG_RIGHT_FLUSH, OnRegRightFlush)
	ON_COMMAND(ID_REG_RIGHT_MODIFY, OnRegRightModify)
	ON_UPDATE_COMMAND_UI(ID_REG_RIGHT_MODIFY, OnUpdateRegRightModify)
	ON_COMMAND(ID_REG_RIGHT_RENAME, OnRegRightRename)
	ON_UPDATE_COMMAND_UI(ID_REG_RIGHT_RENAME, OnUpdateRegRightRename)
	ON_COMMAND(ID_REG_RIGHT_CREATE_INT, OnRegRightCreateInt)
	ON_MESSAGE(WM_REGLEFTDBCLICK,OnRegLeftDbClick)
	ON_MESSAGE(WM_REGLEFTRCLICK,OnRegLeftRClick)
	ON_MESSAGE(WM_REGRIGHTRBCLICK,OnRegRightRClick)
	ON_MESSAGE(WM_SETMYCURSOR,OnSetMyCursor)
	ON_MESSAGE(WM_REGRIGHTRENAMEOK, OnRegRightRenameOk)
	ON_UPDATE_COMMAND_UI(IDS_MYDIRFILES, OnUpdateMyFiles)
	ON_WM_COPYDATA()
	ON_WM_SETCURSOR()
	ON_WM_SIZE()
	ON_WM_CLOSE()
END_MESSAGE_MAP()